import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/home/Navbar";
import Footer from "@/components/home/Footer";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800","900"],
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "Beyond AI - Transforming Businesses with Intelligent Solutions",
  description: "Generated by Beyond AI - Your Partner in Digital Transformation. Explore our innovative AI solutions, enterprise software, and cutting-edge applications designed to revolutionize your business operations. Discover how Beyond AI can help you harness the power of artificial intelligence to drive growth, efficiency, and success in the digital age.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <html
      lang="en"
      className={`${outfit.variable} `}
    >
      <head>
        
        <meta name="color-scheme" content="light" />
      </head>
<Navbar/>
      <body className="font-outfit antialiased bg-white">
        {children}
      </body>
       <Footer/>
    </html>
  );
}
